### ISSUE TITLE
Need table of content

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-architecture/ui-best-practices#1]
Documents there easily get very long and have a very helpful structure (separate graphics, choosing widgets, encouraged workflows...). The doc should have a ToC to be more usable.

**Comment by guw** [comment]
Another point that was raised last week during a discussion is splitting up the document. Currently it's a UI guide, focusing a lot on style (eg., icons). It might make sense to split it up into a UI style guide and UX guide.

We might also be able to split it into multiple documents and linking between then. FWIW, I'm not bound to a particular markup language. I just picked Asciidoc.

**Comment by mickaelistria** [comment]
Yeah splitting docs make sense. WDYT about calling this doc "Graphical Guidelines", and bootstrap a new doc about "User workflows guidelines" and another about "Progress report guidelines"... ?

**Comment by guw** [comment]
I'm not sure. Where would you recommend things like notifications, modal dialogs, menu structuring/naming, general recommendations?

**Comment by mickaelistria** [comment]
A risk is that all recommendation we'll make will be pretty general, so we cannot have "General recommendations". Maybe one page for each:
* Dialogs recommendation (modality, labels, progress report...)
* Menus and navigation recommendation (structures, labels...)
* Notification recommendations
* Progress report recommendations
* Graphical recommendation
* ....
?

**Comment by guw** [comment]
That seems to make a lot sense. I like the page-per-theme/topic proposal.
